/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package isi_2022_ii_proyecto;


import isi_2022_ii_proyecto.Conexion.ConexionBD;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Edwin Rafael
 */
public class Inicio extends javax.swing.JFrame {
    
 

    /**
     * Creates new form Inicio
     */
   
    public Inicio() {
        initComponents(); 
        this.setLocationRelativeTo(null);
        jTextField1.setOpaque(false);
        jPasswordField2.setOpaque(false);
    
       
    }
    
    
    private boolean validar(){
       
        char [] arrayC=jPasswordField2.getPassword();
        String acceso= new String(arrayC);
        
        if(jTextField1.getText().isEmpty() || acceso.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Los valores estan vacios");
            return false;
        }else{
            return true;
        }
    }
    
    private void logearse(){
        ConexionBD conexion = new ConexionBD();
         Connection con = conexion.conexion();
         int usuario;
        String acceso;
        char [] arrayC=jPasswordField2.getPassword();
        String vacceso="";
        
        usuario=Integer.parseInt(jTextField1.getText());
        acceso= new String(arrayC);
        String Sql;
        
        Sql = "Select u.Contrase from Usuarios u Where u.IdUsuario="+usuario;
         try {
            Statement st = (Statement) con.createStatement();
            ResultSet rs = st.executeQuery(Sql);
            while (rs.next()) {
                vacceso = rs.getString("Contrase");
            }
            con.close();
        
        
        
         }catch(Exception e){
             System.out.println("Error "+e.getMessage());
          
                    }
         
         
         System.out.println("contra ingre "+acceso);
         System.out.println("user "+String.valueOf(usuario));
         System.out.println("contra reci "+vacceso);
         if(acceso.equals(vacceso)){
             Empleados e = new Empleados();
             e.setVisible(true);
             this.dispose();
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelRound1 = new isi_2022_ii_proyecto.Recursos.PanelRound();
        panelRound2 = new isi_2022_ii_proyecto.Recursos.PanelRound();
        panelRound3 = new isi_2022_ii_proyecto.Recursos.PanelRound();
        panelRound4 = new isi_2022_ii_proyecto.Recursos.PanelRound();
        panelRound5 = new isi_2022_ii_proyecto.Recursos.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rSLabelHora1 = new rojeru_san.RSLabelHora();
        rSLabelBorderRound1 = new rojeru_san.rslabel.RSLabelBorderRound();
        rSButtonRound1 = new rojerusan.RSButtonRound();
        rSMTextFull1 = new rojeru_san.RSMTextFull();
        rSMPassView1 = new rojeru_san.RSMPassView();
        rSProgressCircleAnimated1 = new rojerusan.RSProgressCircleAnimated();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(252, 235, 255));

        jPanel1.setPreferredSize(new java.awt.Dimension(1444, 834));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(110);
        panelRound1.setRoundBottomRight(110);
        panelRound1.setRoundTopLeft(110);
        panelRound1.setRoundTopRight(110);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound2.setBackground(new java.awt.Color(19, 99, 223));
        panelRound2.setRoundBottomRight(110);
        panelRound2.setRoundTopRight(110);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound3.setBackground(new java.awt.Color(255, 255, 255));
        panelRound3.setRoundBottomLeft(100);
        panelRound3.setRoundBottomRight(100);
        panelRound3.setRoundTopLeft(100);
        panelRound3.setRoundTopRight(100);

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        panelRound2.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 20, 20));

        panelRound4.setBackground(new java.awt.Color(255, 255, 255));
        panelRound4.setRoundBottomLeft(100);
        panelRound4.setRoundBottomRight(100);
        panelRound4.setRoundTopLeft(100);
        panelRound4.setRoundTopRight(100);

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        panelRound2.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 20, 20));

        panelRound5.setBackground(new java.awt.Color(255, 255, 255));
        panelRound5.setRoundBottomLeft(100);
        panelRound5.setRoundBottomRight(100);
        panelRound5.setRoundTopLeft(100);
        panelRound5.setRoundTopRight(100);

        javax.swing.GroupLayout panelRound5Layout = new javax.swing.GroupLayout(panelRound5);
        panelRound5.setLayout(panelRound5Layout);
        panelRound5Layout.setHorizontalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        panelRound5Layout.setVerticalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        panelRound2.add(panelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 20, 20));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Book", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SYSTEM");
        panelRound2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Book", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("GEVEC");
        panelRound2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("contacto con el Administrador");
        panelRound2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 210, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Si aún no cuentas con un usuario, ponte en contacto ");
        panelRound2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 390, 30));

        panelRound1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 410, 460));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/isi_2022_ii_proyecto/Imagenes/usuario.png"))); // NOI18N
        panelRound1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 110, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(19, 99, 223));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Inicia session con tu cuenta");
        panelRound1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 230, 30));
        panelRound1.add(rSLabelHora1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 110, -1));

        rSLabelBorderRound1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rSLabelBorderRound1.setText("Recuperar Acceso");
        panelRound1.add(rSLabelBorderRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 250, 40));

        rSButtonRound1.setBackground(new java.awt.Color(19, 99, 223));
        rSButtonRound1.setText("Iniciar Sesion");
        rSButtonRound1.setColorHover(new java.awt.Color(255, 255, 255));
        rSButtonRound1.setColorTextHover(new java.awt.Color(19, 99, 223));
        panelRound1.add(rSButtonRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 250, -1));

        rSMTextFull1.setPlaceholder("Ingresa tu usuario...");
        panelRound1.add(rSMTextFull1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));
        panelRound1.add(rSMPassView1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        rSProgressCircleAnimated1.setForeground(new java.awt.Color(19, 99, 223));
        rSProgressCircleAnimated1.setString("");
        rSProgressCircleAnimated1.setVisible(false);
        panelRound1.add(rSProgressCircleAnimated1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 40, 40));

        jPanel1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 850, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1167, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private isi_2022_ii_proyecto.Recursos.PanelRound panelRound1;
    private isi_2022_ii_proyecto.Recursos.PanelRound panelRound2;
    private isi_2022_ii_proyecto.Recursos.PanelRound panelRound3;
    private isi_2022_ii_proyecto.Recursos.PanelRound panelRound4;
    private isi_2022_ii_proyecto.Recursos.PanelRound panelRound5;
    private rojerusan.RSButtonRound rSButtonRound1;
    private rojeru_san.rslabel.RSLabelBorderRound rSLabelBorderRound1;
    private rojeru_san.RSLabelHora rSLabelHora1;
    private rojeru_san.RSMPassView rSMPassView1;
    private rojeru_san.RSMTextFull rSMTextFull1;
    private rojerusan.RSProgressCircleAnimated rSProgressCircleAnimated1;
    // End of variables declaration//GEN-END:variables
}
