/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package isi_2022_ii_proyecto.Recursos;

import isi_2022_ii_proyecto.ActualizarCaja;
import isi_2022_ii_proyecto.ActualizarNuevaContrase;
import isi_2022_ii_proyecto.CambiarContrase;
import rojeru_san.complementos.RSUtilities;

/**
 *
 * @author Edwin Rafael
 */
public class LoginVentana extends javax.swing.JFrame {

    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }
    int idusuario;
    CambiarContrase cc;

    public void setCc(CambiarContrase cc) {
        this.cc = cc;
    }

    /**
     * Creates new form VentanaEmergente1
     */
    public LoginVentana() {
        RSUtilities.setFullScreenJFrame(this);
        initComponents();
        RSUtilities.setOpaqueWindow(this, false);
        RSUtilities.setOpacityComponent(this.jPanel1, 150);
        rSProgressCircleAnimated1.setVisible(false);
        rSLabelIcon1.setVisible(false);
        rSLabelAnimated1.setVisible(false);
 
    }
    
    
    
    public void iniciarconteo(){
        ConteoCambiorContra n1 = new ConteoCambiorContra();
        n1.setBarra(rSProgressCircleAnimated1);
        n1.setInicio(this);
        Thread h1 = new Thread(n1);
        h1.start();
    }
    
    
    public void mensajevalidado(){
        jLabel7.setText("Token Validado Exitosamente");
        rSProgressCircleAnimated1.setVisible(false);
        rSLabelIcon1.setVisible(true);
        rSLabelAnimated1.setVisible(true);
        
        Conteos n1 = new Conteos();
        n1.setInicio(this);
        Thread h1 = new Thread(n1);
        h1.start();
    }
    
    
    public void GoCambiarC(){
        ActualizarNuevaContrase acn = new ActualizarNuevaContrase();
        acn.setIdusuario(idusuario);
        acn.setVisible(true);
        this.dispose();
        cc.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rSPanelOpacity1 = new RSMaterialComponent.RSPanelOpacity();
        rSLabelIcon1 = new RSMaterialComponent.RSLabelIcon();
        rSProgressCircleAnimated1 = new rojerusan.RSProgressCircleAnimated();
        jLabel7 = new javax.swing.JLabel();
        rSLabelAnimated1 = new rojeru_san.rslabel.RSLabelAnimated();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        rSPanelOpacity1.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelOpacity1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSLabelIcon1.setForeground(new java.awt.Color(19, 99, 223));
        rSLabelIcon1.setToolTipText("");
        rSLabelIcon1.setFocusable(false);
        rSLabelIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SECURITY);
        rSPanelOpacity1.add(rSLabelIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 260, 260));

        rSProgressCircleAnimated1.setForeground(new java.awt.Color(19, 99, 223));
        rSProgressCircleAnimated1.setColorText(new java.awt.Color(19, 99, 223));
        rSProgressCircleAnimated1.setFocusable(false);
        rSProgressCircleAnimated1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSProgressCircleAnimated1.setVelocidad(20);
        rSProgressCircleAnimated1.setVerifyInputWhenFocusTarget(false);
        rSPanelOpacity1.add(rSProgressCircleAnimated1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 320, 280));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(19, 99, 223));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Validando Token de Acceso");
        rSPanelOpacity1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 320, -1));

        rSLabelAnimated1.setText("Redirigiendo…");
        rSLabelAnimated1.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        rSPanelOpacity1.add(rSLabelAnimated1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSPanelOpacity1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSPanelOpacity1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private rojeru_san.rslabel.RSLabelAnimated rSLabelAnimated1;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon1;
    private RSMaterialComponent.RSPanelOpacity rSPanelOpacity1;
    private rojerusan.RSProgressCircleAnimated rSProgressCircleAnimated1;
    // End of variables declaration//GEN-END:variables
}
