/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package isi_2022_ii_proyecto.Recursos;

import RSMaterialComponent.RSLabelIcon;
import RSMaterialComponent.RSPanelOpacity;
import isi_2022_ii_proyecto.ActualizarAlmacen;
import isi_2022_ii_proyecto.ActualizarBanco;
import isi_2022_ii_proyecto.ActualizarCaja;
import isi_2022_ii_proyecto.ActualizarCategoria;
import isi_2022_ii_proyecto.ActualizarCliente;
import isi_2022_ii_proyecto.ActualizarEmpleado;
import isi_2022_ii_proyecto.ActualizarEnvio;
import isi_2022_ii_proyecto.ActualizarInventario;
import isi_2022_ii_proyecto.ActualizarLogistica;
import isi_2022_ii_proyecto.ActualizarNuevaContrase;
import isi_2022_ii_proyecto.ActualizarProductos;
import isi_2022_ii_proyecto.ActualizarProveedor;
import isi_2022_ii_proyecto.ActualizarUsuarios;
import isi_2022_ii_proyecto.AgregarAlmacen;
import isi_2022_ii_proyecto.AgregarCaja;
import isi_2022_ii_proyecto.AgregarCategoria;
import isi_2022_ii_proyecto.AgregarClientes;
import isi_2022_ii_proyecto.AgregarCuentaBancaria;
import isi_2022_ii_proyecto.AgregarEmpleado;
import isi_2022_ii_proyecto.AgregarEnvio;
import isi_2022_ii_proyecto.AgregarBanco;
import isi_2022_ii_proyecto.AgregarInventario;
import isi_2022_ii_proyecto.AgregarLogistica;
import isi_2022_ii_proyecto.AgregarProducto;
import isi_2022_ii_proyecto.AgregarProveedor;
import isi_2022_ii_proyecto.AgregarUsuario;
import isi_2022_ii_proyecto.Almacen;
import isi_2022_ii_proyecto.AperturarCajas;
import isi_2022_ii_proyecto.Banco;
import isi_2022_ii_proyecto.BancosMovimientos;
import isi_2022_ii_proyecto.BuscarCaja;
import isi_2022_ii_proyecto.BuscarCuentaB;
import isi_2022_ii_proyecto.BuscarProducto;
import isi_2022_ii_proyecto.Caja;
import isi_2022_ii_proyecto.CambiarContrase;
import isi_2022_ii_proyecto.Categoria;
import isi_2022_ii_proyecto.Cliente;
import isi_2022_ii_proyecto.Compras;
import isi_2022_ii_proyecto.Conexion.ConexionBD;
//import isi_2022_ii_proyecto.Dashboard;
import isi_2022_ii_proyecto.Empleados;
import isi_2022_ii_proyecto.Envio;
import isi_2022_ii_proyecto.Facturas;
import isi_2022_ii_proyecto.GenerarVenta;
import isi_2022_ii_proyecto.Inicio;
import isi_2022_ii_proyecto.Inventario;
import isi_2022_ii_proyecto.Logistica;
import isi_2022_ii_proyecto.Menu;
import isi_2022_ii_proyecto.ModificarCuentaB;
import isi_2022_ii_proyecto.POS;
import isi_2022_ii_proyecto.POSCLOUD;
import isi_2022_ii_proyecto.POS1;
import isi_2022_ii_proyecto.PrecioHistorico;
import isi_2022_ii_proyecto.Productos;
import isi_2022_ii_proyecto.Proveedores;
import isi_2022_ii_proyecto.RecuperarContraseña;
import isi_2022_ii_proyecto.TablaProductos;
import isi_2022_ii_proyecto.TablaProductosCompras;
import isi_2022_ii_proyecto.TipoVenta;
import isi_2022_ii_proyecto.Usuario;
import isi_2022_ii_proyecto.Ventas;
import isi_2022_ii_proyecto.VentasEmpleado;
import isi_2022_ii_proyecto.VerificarOrden;
import isi_2022_ii_proyecto.VerificarOrdenADomicilio;
import java.sql.Connection;
import javax.swing.JLabel;
import javax.swing.JPanel;
import rojeru_san.complementos.RSUtilities;
import rojerusan.RSButtonRound;

/**
 *
 * @author Edwin Rafael
 */
public class VentanaErrorDeconexion3 extends javax.swing.JFrame {
 
 
ConexionBD b;

    public void setB(ConexionBD b) {
        this.b = b;
    }
   

    /**
     * Creates new form VentanaEmergente1
     */
    public VentanaErrorDeconexion3() {
        RSUtilities.setFullScreenJFrame(this);
        initComponents();
        RSUtilities.setOpaqueWindow(this, false);
        RSUtilities.setOpacityComponent(this.jPanel1, 150);
    }
    
    

    
    
   
    
    public void ejecutar(){
     b.setPass(true);
     b.errores();
     this.dispose();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rSPanelOpacity1 = new RSMaterialComponent.RSPanelOpacity();
        rSLabelIcon1 = new RSMaterialComponent.RSLabelIcon();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rSButtonRound1 = new rojerusan.RSButtonRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        rSPanelOpacity1.setBackground(new java.awt.Color(0, 55, 133));
        rSPanelOpacity1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSLabelIcon1.setForeground(new java.awt.Color(255, 255, 255));
        rSLabelIcon1.setToolTipText("");
        rSLabelIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ERROR);
        rSPanelOpacity1.add(rSLabelIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 150, 140));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 40)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ERROR");
        rSPanelOpacity1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 550, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Franklin Gothic Book", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("ERROR DE CONEXION");
        rSPanelOpacity1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        rSButtonRound1.setBackground(new java.awt.Color(0, 153, 102));
        rSButtonRound1.setText("Reconectar");
        rSButtonRound1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rSButtonRound1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound1ActionPerformed(evt);
            }
        });
        rSPanelOpacity1.add(rSButtonRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSPanelOpacity1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSPanelOpacity1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonRound1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound1ActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_rSButtonRound1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaErrorDeconexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaErrorDeconexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaErrorDeconexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaErrorDeconexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaErrorDeconexion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private rojerusan.RSButtonRound rSButtonRound1;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon1;
    private RSMaterialComponent.RSPanelOpacity rSPanelOpacity1;
    // End of variables declaration//GEN-END:variables
}
